version: "3.9"

services:
  backend:
      build: 
        context: ./backend/
      command: python manage.py runserver 0.0.0.0:8000
      
      ports:
        - "8000:8000"
  frontend:
      build: 
        context: ./Frontend/front/
      volumes:
        - reacta_build/react/build
      ports:
        - "3000:3000"
      command: npm start
      
